spring:
  datasource:
    url: "jdbc:h2:mem:testdb;MODE=ORACLE;DB_CLOSE_DELAY=-1;"
    platform: h2
    driver-class-name: "org.h2.Driver"
    username: sa
    password:
    dbcp:
      default-auto-commit: false
  h2:
    console:
      path: /admin/h2-console
      enabled: true
